# Generated by Django 2.2 on 2019-04-02 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='reverse',
            new_name='back',
        ),
    ]
