# Generated by Django 2.2 on 2019-04-03 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='favorited_by',
            field=models.ManyToManyField(null=True, related_name='favorited', to=settings.AUTH_USER_MODEL),
        ),
    ]
