# Generated by Django 2.2 on 2019-04-07 16:25

from django.db import migrations
from django.conf import settings
from django.utils.text import slugify

import os.path
import csv

def load_easy_deck(apps, schema_editor):
    """Read CSV file of comment data and add it to the posts"""
    Card = apps.get_model('core', 'Card')
    User = apps.get_model('auth', 'User')
    Deck = apps.get_model('core', 'Deck')

    datapath = os.path.join(settings.BASE_DIR, 'initial_data')
    datafile = os.path.join(datapath, 'easy_deck.csv')

    with open(datafile) as file:
        reader = csv.DictReader(file)
        for row in reader:

            deck_user, _ = User.objects.get_or_create(username=row['user'])
    
            deck = Deck(
                user = deck_user,
                name = row['name'],
                slug = slugify(row['name']),
            )
            deck.save()

            card_strings = row['cards'].split('/')
            card_objects = []
            for card_string in card_strings:
                card = Card.objects.filter(front=card_string)[0]
                card_objects.append(card)

            for card in card_objects:
                deck.cards.add(card)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190407_1223'),
    ]

    operations = [migrations.RunPython(load_easy_deck)
    ]
