# Generated by Django 2.2 on 2019-04-02 21:05

from django.db import migrations
from django.conf import settings
from django.utils.text import slugify

import os.path
import csv

def load_cards(apps, schema_editor):
    """Read CSV file of comment data and add it to the posts"""
    Card = apps.get_model('core', 'Card')
    User = apps.get_model('auth', 'User')

    datapath = os.path.join(settings.BASE_DIR, 'initial_data')
    datafile = os.path.join(datapath, 'cards.csv')

    with open(datafile) as file:
        reader = csv.DictReader(file)
        for row in reader:

            card_user, _ = User.objects.get_or_create(username=row['user'])

            card = Card(
                user = card_user,
                front = row['front'],
                back = row['back'],
                slug = slugify(row['back'])[:50]
            )
            card.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190402_1704'),
    ]

    operations = [migrations.RunPython(load_cards)
    ]
