# Generated by Django 2.2 on 2019-04-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190403_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='category',
        ),
        migrations.AddField(
            model_name='card',
            name='frontimage',
            field=models.ImageField(blank=True, null=True, upload_to='static/card_images/'),
        ),
    ]
